package es.zgames.utils;

import es.zgames.laguerradelasvajillasfree.R;
import android.widget.ImageView;

public class AnimationsContainer {     
	
	// single instance procedures     
	
	private static AnimationsContainer mInstance;      
	
	private AnimationsContainer() {     
		
	};      
	
	public static AnimationsContainer getInstance() {         
		if (mInstance == null)             
			mInstance = new AnimationsContainer();         
		return mInstance;     
	}      
	
	
	
	// animation splash screen frames     
	private int[] mSplashAnimFrames = { 
			R.drawable.splash_z_games001, 
			R.drawable.splash_z_games003, 
			R.drawable.splash_z_games005, 
			R.drawable.splash_z_games007, 
			R.drawable.splash_z_games009, 
			R.drawable.splash_z_games011, 
			R.drawable.splash_z_games013, 
			R.drawable.splash_z_games015, 
			R.drawable.splash_z_games017, 
			R.drawable.splash_z_games019, 
			R.drawable.splash_z_games021, 
			R.drawable.splash_z_games023, 
			R.drawable.splash_z_games025, 
			R.drawable.splash_z_games027, 
			R.drawable.splash_z_games029, 
			R.drawable.splash_z_games031, 
			R.drawable.splash_z_games033, 
			R.drawable.splash_z_games035, 
			R.drawable.splash_z_games037, 
			R.drawable.splash_z_games039, 
			R.drawable.splash_z_games041, 
			R.drawable.splash_z_games043, 
			R.drawable.splash_z_games045, 
			R.drawable.splash_z_games047, 
			R.drawable.splash_z_games049, 
			R.drawable.splash_z_games051, 
			R.drawable.splash_z_games053, 
			R.drawable.splash_z_games055, 
			R.drawable.splash_z_games057, 
			R.drawable.splash_z_games059, 
			R.drawable.splash_z_games061, 
			R.drawable.splash_z_games063, 
			R.drawable.splash_z_games065, 
			R.drawable.splash_z_games067, 
			R.drawable.splash_z_games069, 
			R.drawable.splash_z_games071, 
			R.drawable.splash_z_games073, 
			R.drawable.splash_z_games075, 
			R.drawable.splash_z_games077, 
			R.drawable.splash_z_games079, 
			R.drawable.splash_z_games081, 
			R.drawable.splash_z_games083, 
			R.drawable.splash_z_games085, 
			R.drawable.splash_z_games087, 
			R.drawable.splash_z_games089, 
			R.drawable.splash_z_games091, 
			R.drawable.splash_z_games093, 
			R.drawable.splash_z_games095, 
			R.drawable.splash_z_games097, 
			R.drawable.splash_z_games099, 
			R.drawable.splash_z_games101, 
			R.drawable.splash_z_games103, 
			R.drawable.splash_z_games105, 
			R.drawable.splash_z_games107, 
			R.drawable.splash_z_games109, 
			R.drawable.splash_z_games111, 
			R.drawable.splash_z_games113, 
			R.drawable.splash_z_games115, 
			R.drawable.splash_z_games117, 
			R.drawable.splash_z_games119, 
			R.drawable.splash_z_games121, 
			R.drawable.splash_z_games123, 
			R.drawable.splash_z_games125, 
			R.drawable.splash_z_games127, 
			R.drawable.splash_z_games129, 
			R.drawable.splash_z_games131, 
			R.drawable.splash_z_games133, 
			R.drawable.splash_z_games135, 
			R.drawable.splash_z_games137, 
			R.drawable.splash_z_games139, 
			R.drawable.splash_z_games141, 
			R.drawable.splash_z_games143, 
			R.drawable.splash_z_games145, 
			R.drawable.splash_z_games147, 
			R.drawable.splash_z_games149, 
			R.drawable.splash_z_games151, 
			R.drawable.splash_z_games153, 
			R.drawable.splash_z_games155, 
			R.drawable.splash_z_games157, 
			R.drawable.splash_z_games159, 
			R.drawable.splash_z_games161, 
			R.drawable.splash_z_games163, 
			R.drawable.splash_z_games165, 
			R.drawable.splash_z_games167, 
			R.drawable.splash_z_games169, 
			R.drawable.splash_z_games171, 
			R.drawable.splash_z_games173, 
			R.drawable.splash_z_games175, 
			R.drawable.splash_z_games177, 
			R.drawable.splash_z_games179, 
			R.drawable.splash_z_games181, 
			R.drawable.splash_z_games183, 
			R.drawable.splash_z_games185, 
			R.drawable.splash_z_games187, 
			R.drawable.splash_z_games189, 
			R.drawable.splash_z_games191, 
			R.drawable.splash_z_games193, 
			R.drawable.splash_z_games195, 
			R.drawable.splash_z_games197, 
			R.drawable.splash_z_games199, 
			R.drawable.splash_z_games201, 
			R.drawable.splash_z_games203, 
			R.drawable.splash_z_games205, 
			R.drawable.splash_z_games207, 
			R.drawable.splash_z_games209, 
			R.drawable.splash_z_games211, 
			R.drawable.splash_z_games213, 
			R.drawable.splash_z_games215, 
			R.drawable.splash_z_games217, 
			R.drawable.splash_z_games219, 
			R.drawable.splash_z_games221, 
			R.drawable.splash_z_games223, 
			R.drawable.splash_z_games225, 
			R.drawable.splash_z_games227, 
			R.drawable.splash_z_games229, 
			R.drawable.splash_z_games231, 
			R.drawable.splash_z_games233, 
			R.drawable.splash_z_games235, 
			R.drawable.splash_z_games237, 
			R.drawable.splash_z_games239, 
			R.drawable.splash_z_games241, 
			R.drawable.splash_z_games243, 
			R.drawable.splash_z_games245, 
			R.drawable.splash_z_games247, 
			R.drawable.splash_z_games249, 
			R.drawable.splash_z_games251, 
			R.drawable.splash_z_games253, 
			R.drawable.splash_z_games255, 
			R.drawable.splash_z_games257, 
			R.drawable.splash_z_games259, 
			R.drawable.splash_z_games261, 
			R.drawable.splash_z_games263, 
			R.drawable.splash_z_games265,			
			R.drawable.splash_z_games269,			 
			R.drawable.splash_z_games273,			 
			R.drawable.splash_z_games277, 
			R.drawable.splash_z_games279,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games280,
			R.drawable.splash_z_games281,			
			R.drawable.splash_z_games281,
			R.drawable.splash_z_games281,
			R.drawable.splash_z_games281,
			R.drawable.splash_z_games281,
			R.drawable.splash_z_games281,			
			R.drawable.splash_z_games281,
			R.drawable.splash_z_games281,
			R.drawable.splash_z_games281,
			R.drawable.splash_z_games281,			
			R.drawable.splash
	};       
	
	private int[] mRadarAnimFrames = { 
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06,
			R.drawable.radar01, 
			R.drawable.radar02, 
			R.drawable.radar03, 
			R.drawable.radar04, 
			R.drawable.radar05, 
			R.drawable.radar06
			
	};
		
	/**      
	 * * @param imageView      
	 * * @return splash screen animation      
	 * */     
	
	public FramesSequenceAnimation createSplashAnim(ImageView imageView) {         
		return new FramesSequenceAnimation(imageView, mSplashAnimFrames, "splash",1000);     
	}      
	
	public FramesSequenceAnimation createRadarAnim(ImageView imageView) {         
		return new FramesSequenceAnimation(imageView, mRadarAnimFrames, "radar",3000);     
	}   
	
	
	/**      
	 * * AnimationPlayer. Plays animation frames sequence in loop      
	 * */     
	
	
} 